# Generated by Django 3.2.9 on 2021-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_img_url',
            field=models.URLField(),
        ),
    ]
